FerrePro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from django.conf import settings
from Ferre.views import Login
from Ferre.views import Logout
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', Login.as_view(), name='login'),
    url(r'^logout/', Logout.as_view(), name='logout'),
    url(r'^usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.conf.urls import url
from usuarios.views import Inicio, ListaClientes, AgregarClientes,ListadoVentas,ListaProveedores, ModificarClientes,Agregarproveedor
from usuarios.views import VerCliente, VerProveedor,VerVenta, ModificarProveedor,ListadoDomicilios, ListaProductos, AgregarProducto,AgregarStock, AgregarVenta
from usuarios.views import ActualizarDomicilio

urlpatterns = [
    url(r'^inicio/', Inicio.as_view(), name='inicio'),
    url(r'listadoclientes', ListaClientes.as_view(), name='listadoclientes'),
    url(r'agregarcliente', AgregarClientes.as_view(), name='agregarcliente'),
    url(r'listadoproveedores', ListaProveedores.as_view(), name='listadoproveedores'),
    url(r'agregarproveedor', Agregarproveedor.as_view(), name='agregarproveedor'),
    url(r'vercliente/(?P<Idcliente>\w+)', VerCliente.as_view(), name='vercliente'),
    url(r'verproveedor/(?P<Idproveedor>\w+)', VerProveedor.as_view(), name='verproveedor'),
    url(r'modificarcliente/(?P<identificador>\w+)', ModificarClientes.as_view(), name='modificarcliente'),
    url(r'modificarproveedor/(?P<identificador>\w+)', ModificarProveedor.as_view(), name='modificarproveedor'),
    url(r'listadoproductos', ListaProductos.as_view(), name='listadoproductos'),
    url(r'agregarproducto', AgregarProducto.as_view(), name='agregarproducto'),
    url(r'agregarstock/(?P<identificador>\w+)', AgregarStock.as_view(), name='agregarstock'),
    url(r'agregarventa', AgregarVenta.as_view(), name='agregarventa'),
    url(r'listadoventas/', ListadoVentas.as_view(), name='listadoventas'),
    url(r'listadodomicilios/', ListadoDomicilios.as_view(), name='listadodomicilios'),
    url(r'verventa/(?P<idventa>\w+)', VerVenta.as_view(), name='verventa'),
    url(r'actualizardomi/(?P<identificador>\w+)', ActualizarDomicilio.as_view(), name='actualizardomi'),

]

usuarios/views.py
import os
import socket
from django.shortcuts import render
from django.conf import settings
import json
from django.http import JsonResponse
from django.http import HttpResponse
from django.core import serializers
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
from datetime import datetime
from django.contrib import auth
from Ferre.models import Usuario, Clientes, Proveedor, Productos, Ventas, Domicilio, RegistroVentas
from Ferre.forms import AddClientes, AddProveedor, UpdateClientes, UpdateProveedor, AddProductos, AddStock, AddVcliente,UpdateDomicilio

class Inicio(LoginRequiredMixin, View):
    login_url = '/'
    template_name = 'usuarios/inicio.html'

    def get(self, request):
        try:
            nombre = open('static/serial/NombreProyecto.txt', 'r')
            proyectov = nombre.read()
            version = open('static/serial/Version.txt', 'r')
            versionp = version.read()
            datos = Usuario.objects.get(usuid=request.user.pk)
            stock = Productos.objects.all()
            domicilios = Domicilio.objects.filter(Estado='Pendiente')
            contdomi = Domicilio.objects.filter(Estado='Pendiente').count()
            ventas = Ventas.objects.all().order_by('-IdVentas')[:10]
            fechaexp = (datetime.today())
            dia = fechaexp.day
            ciclo = fechaexp.month
            ano1 = fechaexp.year
            # Los argumentos serán: Año, Mes, Día, Hora, Minutos, Segundos, Milisegundos.
            new_date = datetime(ano1, ciclo, dia, 1, 00, 00, 00000)
            new_date2 = datetime(ano1, ciclo, dia, 23, 59, 59, 00000)
            cventas = Ventas.objects.filter(Fecha__gte=new_date, Fecha__lte=new_date2).all()

            contar = 0
            for i in cventas:
                if i.pk >= 1:
                    contar += 1

            valorventas = 0
            for i in cventas:
                    valorventas += i.Valor

            cantstock = 0
            for i in stock:
                cantstock += i.Stock

            return render(request,
                          self.template_name,{'proyecto': proyectov,'version':versionp,'domi':domicilios, 'cantstock':cantstock,'stock': stock,
                                              'ventas': ventas,'contar':contar, 'valorventas':valorventas,'contdomi':contdomi}
                            )
        except Usuario.DoesNotExist:
            return render(request, "pages-404.html")

class ListaClientes(LoginRequiredMixin, View):
    login_url = '/'
    template_name = 'usuarios/listadoclientes.html'

    def get(self, request):
        try:
            nombre = open('static/serial/NombreProyecto.txt', 'r')
            proyectov = nombre.read()
            version = open('static/serial/Version.txt', 'r')
            versionp = version.read()
            datos = Usuario.objects.get(usuid=request.user.pk)
            clientes = Clientes.objects.all()
            return render(request,
                          self.template_name,{'proyecto': proyectov,'version':versionp,'clientes':clientes}
                            )
        except Usuario.DoesNotExist:
            return render(request, "pages-404.html")

class AgregarClientes(LoginRequiredMixin, View):
    login_url = '/'
    template_name = 'usuarios/agregarcliente.html'
    form = AddClientes

    def get(self, request):
        try:
            nombre = open('static/serial/NombreProyecto.txt', 'r')
            proyectov = nombre.read()
            version = open('static/serial/Version.txt', 'r')
            versionp = version.read()
            datos = Usuario.objects.get(usuid=request.user.pk)
            form = self.form
            return render(request,
                          self.template_name,{'proyecto': proyectov,'version':versionp,'formulariocliente':form,}
                            )
        except Usuario.DoesNotExist:
            return render(request, "pages-404.html")

    def post(self, request):
        try:
            datos = Usuario.objects.get(usuid=request.user.pk)
            form = self.form(request.user, request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.INFO, 'la informacion del cliente se agrego correctamente')
                return HttpResponseRedirect(reverse('usuarios:listadoclientes'))

            else:
                messages.add_message(request, messages.ERROR, 'No se puedo agregar la informacion del cliente')
                return HttpResponseRedirect(reverse('usuarios:agregarcliente'))

        except Usuario.DoesNotExist:
            return render(request, "pages-404.html")


class ModificarClientes(LoginRequiredMixin, View):
    login_url = '/'
    template_name = 'usuarios/modificarcliente.html'
    form = UpdateClientes

    def get(self, request, identificador):
        try:
            nombre = open('static/serial/NombreProyecto.txt', 'r')
            proyectov = nombre.read()
            version = open('static/serial/Version.txt', 'r')
            versionp = version.read()
            IdCliente = identificador
            datos = Usuario.objects.get(usuid=request.user.pk)
            datoscliente = Clientes.objects.get(Idcliente=IdCliente)
            form = self.form(instance=datoscliente)
            return render(request,
                          self.template_name,{'proyecto': proyectov,'version':versionp,'formulariocliente':form,}
                            )
        except Usuario.DoesNotExist:
            return render(request, "pages-404.html")

    def post(self, request, identificador):
        try:
            IdCliente = identificador
            datos = Usuario.objects.get(usuid=request.user.pk)
            datoscliente = Clientes.objects.get(Idcliente=IdCliente)
            form = self.form(request.user, request.POST, instance=datoscliente)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.INFO, 'la informacion del cliente se modifico correctamente')
                return HttpResponseRedirect(reverse('usuarios:inicio'))

            else:
                messages.add_message(request, messages.ERROR, 'No se puedo modificar la informacion del cliente')
                return HttpResponseRedirect(reverse('usuarios:inicio'))

        except Usuario.DoesNotExist:
            return render(request, "pages-404.html")


class ListaProveedores(LoginRequiredMixin, View):
    login_url = '/'
    template_name = 'usuarios/listadoproveedores.html'

    def get(self, request):
        try:
            nombre = open('static/serial/NombreProyecto.txt', 'r')
            proyectov = nombre.read()
            version = open('static/serial/Version.txt', 'r')
            versionp = version.read()
            datos = Usuario.objects.get(usuid=request.user.pk)
            proveedores = Proveedor.objects.all()
            return render(request,
                          self.template_name,{'proyecto': proyectov,'version':versionp,'proveedores':proveedores}
                            )
        except Usuario.DoesNotExist:
            return render(request, "pages-404.html")


class Agregarproveedor(LoginRequiredMixin, View):
    login_url = '/'
    template_name = 'usuarios/agregarproveedor.html'
    form = AddProveedor

    def get(self, request):
        try:
            nombre = open('static/serial/NombreProyecto.txt', 'r')
            proyectov = nombre.read()
            version = open('static/serial/Version.txt', 'r')
            versionp = version.read()
            datos = Usuario.objects.get(usuid=request.user.pk)
            form = self.form
            return render(request,
                          self.template_name,{'proyecto': proyectov,'version':versionp,'formularioproveedor':form,}
                            )
        except Usuario.DoesNotExist:
            return render(request, "pages-404.html")

    def post(self, request):
        try:
            datos = Usuario.objects.get(usuid=request.user.pk)
            form = self.form(request.user, request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.INFO, 'la informacion del proveedor se agrego correctamente')
                return HttpResponseRedirect(reverse('usuarios:inicio'))

            else:
                messages.add_message(request, messages.ERROR, 'No se puedo agregar la informacion del proveedor')
                return HttpResponseRedirect(reverse('usuarios:inicio'))

        except Usuario.DoesNotExist:
            return render(request, "pages-404.html")


class VerCliente(LoginRequiredMixin, View):
    login_url = '/'
    template_name = 'usuarios/verinfocliente.html'

    def get(self, request, Idcliente):
        try:
            nombre = open('static/serial/NombreProyecto.txt', 'r')
            proyectov = nombre.read()
            version = open('static/serial/Version.txt', 'r')
            versionp = version.read()
            datos = Usuario.objects.get(usuid=request.user.pk)
            cliente = Clientes.objects.get(Idcliente=Idcliente)
            return render(request,
                          self.template_name,{'proyecto': proyectov,'version':versionp,
                                              'identificador': cliente.Idcliente,
                                              'nombre': cliente.Nombrecompleto,
                                              'direccion':cliente.Direccion,
                                              'correo': cliente.Correo,
                                              'telefono': cliente.Telefono,
                                              'tipo': cliente.Tipocliente,

usuarios/templates/usuarios/agregarproducto.html
{% extends 'usuarios/base.html' %}
{% load static %}
{% block styles %}
{% endblock %}
{%block title %} <title>AP</title> {%endblock%}
{% block content %}
{% include 'usuarios/alerts.html' %}
                <div class="row g-4 settings-section">
                    <div class="col-12 col-md-4">
                        <h3 class="section-title">Agregar producto</h3>
                        <div class="section-intro">Settings section intro goes here. Lorem ipsum dolor sit amet, consectetur adipiscing elit. <a href="help.html">Learn more</a></div>
                    </div>
                    <div class="col-12 col-md-8">
                        <div class="app-card app-card-settings shadow-sm p-4">
                            
                            <div class="app-card-body">
                                <form method="post" enctype="multipart/form-data" class="settings-form">
                                    {% csrf_token %}
                                    {{ form.non_field_errors }}
                                    {% for field in formularioproductos %}
                                    <div class="mb-3">
                                        <label for="setting-input-2" class="form-label">{{ field.label }}</label>
                                         {{ field }}
                                    </div>
                                    {% endfor %}
                                    <button type="submit" class="btn app-btn-primary" style="width: 100%">Guardar</button>
                                </form>
                                <button class="btn app-btn-primary" style="width: 100%; margin-top: 1rem;" onclick="window.location='{% url 'usuarios:listadoproductos' %}'">Cancelar</button>
                            </div><!--//app-card-body-->
                            
                        </div><!--//app-card-->
                    </div>
                </div><!--//row-->
{% endblock %}
{% block scripts %}
{% endblock %}

usuarios/templates/usuarios/inicio.html
{% extends 'usuarios/base.html' %}
{% load static %}
{% block styles %}
{% endblock %}
{% load humanize %}
{%block title %} <title>Inicio</title> {%endblock%}
{% block content %}
{% include 'usuarios/alerts.html' %}
<div class="row g-4 mb-4">
    <div class="col-6 col-lg-4">
        <div class="app-card app-card-stat shadow-sm h-100">
            <div class="app-card-body p-3 p-lg-4">
                <h4 class="stats-type mb-1">Ventas hoy</h4>
                    <div class="stats-figure">{{contar}}</div>
                        <div class="stats-meta text-success">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1z"/>
                            </svg>
                            0%
                        </div>
            </div><!--//app-card-body-->
            <a class="app-card-link-mask" href="#"></a>
        </div><!--//app-card-->
    </div><!--//col-->
    <div class="col-6 col-lg-4">
        <div class="app-card app-card-stat shadow-sm h-100">
            <div class="app-card-body p-3 p-lg-4">
                <h4 class="stats-type mb-1">Valor</h4>
                    <div class="stats-figure">${{valorventas|intcomma}}</div>
                        <div class="stats-meta text-success">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1z"/>
                            </svg>
                            0%
                        </div>
            </div><!--//app-card-body-->
            <a class="app-card-link-mask" href="#"></a>
        </div><!--//app-card-->
    </div><!--//col-->
    <div class="col-6 col-lg-4">
 <a style="width:100%; margin: 0.2rem;" class="btn app-btn-secondary" href="{% url 'usuarios:agregarventa' %}">Generar venta</a>
<a style="width:100%; margin: 0.2rem;" class="btn app-btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">Consultar stock</a>
<a style="width:100%; margin: 0.2rem;" class="btn app-btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">Agregar cliente</a>
    </div>
</div><!--//row-->
<!--//graficos-->

<div class="row">
<div class="accordion accordion-flush" id="accordionFlushExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingOne">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
       Domicilios pendientes &nbsp<span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
    {{contdomi}}
    <span class="visually-hidden">unread messages</span>
      </button>
    </h2>
    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body">
                                <div class="table-responsive">
                                    <table class="table table-borderless mb-0 text-center">
                                        <thead>
                                            <tr>
                                                <th class="meta">Id</th>
                                                <th class="meta">No venta</th>
                                                <th class="meta">Contacto</th>
                                                <th class="meta">Direccion</th>
                                                <th class="meta">Estado</th>
                                                <th class="meta stat-cell">Opciones</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for domicilio in domi %}
                                        <tr>
                                            <td class="cell">{{domicilio.IdDomicilio}}</td>
                                            <td class="cell">{{domicilio.IdVenta.pk}}</td>
                                            <td class="cell">{{domicilio.Contacto}}</td>
                                            <td class="cell">{{domicilio.Direccion}}</td>
                                            <td class="cell">{{domicilio.Estado}}</td>
                                            <td class="cell">
                                                <div class="row">
                                                    <div class="col-6">
                                                        <a class="btn btn-primary" style="color: white; width: 100%;" href="{% url 'usuarios:verventa' domicilio.IdVenta %}">Ver venta</a>
                                                    </div>
                                                    <div class="col-6">
                                                        <a class="btn btn-primary" style="color: white; width: 100%;" href="{% url 'usuarios:actualizardomi' domicilio.IdDomicilio %}">Entragado</a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
        </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
        Ultimas ventas
      </button>
    </h2>
    <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">
                                <div class="table-responsive">
                                    <table class="table table-borderless mb-0 text-center">
                                        <thead>
                                            <tr>
                                                <th class="meta">No venta</th>
                                                <th class="meta">Fecha</th>
                                                <th class="meta">Valor</th>
                                                <th class="meta">Cant Productos</th>
                                                <th class="meta">Cliente</th>
                                                <th class="meta stat-cell">Opciones</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for venta in ventas %}
                                        <tr>
                                            <td class="cell">{{venta.IdVentas}}</td>
                                            <td class="cell">{{venta.Fecha}}</td>
                                            <td class="cell">${{venta.Valor|intcomma}}</td>
                                            <td class="cell">{{venta.Cantidad}}</td>
                                            <td class="cell">{{venta.Cliente.Nombrecompleto}}</td>
                                            <td class="cell">
                                                <a class="btn btn-primary" style="color: white;" href="{% url 'usuarios:verventa' venta.IdVentas %}">Ver</a>

                                            </td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
        </div>
    </div>
  </div>
</div> 
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Consulta de stock</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
    <div class="col-12 col-lg-12">
            <div class="app-card app-card-basic d-flex flex-column shadow-sm">
                <div class="app-card-header p-3 border-bottom-0">
                    <div class="row">
                        <form class="table-search-form row gx-1 align-items-center">
                            <input style="width: 100%;" type="text" id="search" name="searchorders" class="form-control search-orders" placeholder="Buscar">
                        </form>
                    </div>
                    <div class="row align-items-center gx-3">
                            <div class="table-responsive" style="height:100%; overflow: scroll;">
                                <table class="table app-table-hover mb-0 text-center" id="datatable">
                                    <thead>
                                        <tr>
                                            <th class="cell">Id</th>
                                            <th class="cell">Descripcion</th>
                                            <th class="cell">Categoria</th>
                                            <th class="cell">Stock</th>
                                            <th class="cell">Precio venta</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for producto in stock %}
                                        <tr>
                                            <td class="cell">{{producto.IdProducto|intcomma}}</td>
                                            <td class="cell">{{producto.NombreProducto}}</td>
                                            <td class="cell">{{producto.Categoria}}</td>
                                            <td class="cell">{{producto.Stock}}</td>
                                            <td class="cell"><span>${{producto.PrecioVenta|intcomma}}</span></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                    </div>
                </div>
            </div>
    </div><!--//col-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
<div id="show"></div>
{% endblock %}
{% block scripts %}
<script>
 // Write on keyup event of keyword input element
 $(document).ready(function(){
 $("#search").keyup(function(){
 _this = this;
 // Show only matching TR, hide rest of them
 $.each($("#datatable tbody tr"), function() {
 if($(this).text().toLowerCase().indexOf($(_this).val().toLowerCase()) === -1)
 $(this).hide();
 else
 $(this).show();
 });
 });
});
</script>

{% endblock %}

usuarios/templates/usuarios/listadoproductos.html
{% extends 'usuarios/base.html' %}
{% load static %}
{% block styles %}
{% endblock %}
{% load humanize %}
{%block title %} <title>LP</title> {%endblock%}
{% block content %}
{% include 'usuarios/alerts.html' %}
<!-- Titulo -->
<div class="row g-4 mb-4">
    <div class="row g-3 mb-4 align-items-center justify-content-between">
        <div class="col-auto">
            <h1 class="app-page-title mb-0">Listado de productos</h1>
        </div>
        <div class="col-auto">
            <div class="page-utilities">
                <div class="row g-2 justify-content-start justify-content-md-end align-items-center">
                    <div class="col-auto">
                        <form class="table-search-form row gx-1 align-items-center">
                            <div class="col-auto">
                                <input type="text" id="search" name="searchorders" class="form-control search-orders" placeholder="Buscar">
                            </div>
                        </form>
                    </div><!--//col-->
                    <div class="col-auto">                          
                        <a class="btn app-btn-secondary" href="#">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-download me-1" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                                <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                            </svg>
                            Descargar .xlsx
                        </a>
                    </div>
                    <div class="col-auto">                          
                        <a class="btn app-btn-secondary" href="{% url 'usuarios:agregarproducto' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                              <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                              <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                            </svg>
                            Agregar producto
                        </a>
                    </div>
                </div><!--//row-->
            </div><!--//table-utilities-->
        </div><!--//col-auto-->
    </div><!--//row-->
    <div class="row">
        <div class="tab-content" id="orders-table-tab-content">
            <div class="tab-pane fade show active" id="orders-all" role="tabpanel" aria-labelledby="orders-all-tab">
                <div class="app-card app-card-orders-table shadow-sm mb-5">
                    <div class="app-card-body">
                        <div class="table-responsive">
                            <table class="table app-table-hover mb-0 text-center" id="dataTable">
                                <thead>
                                    <tr>
                                        <th class="cell">Id</th>
                                        <th class="cell">Descripcion</th>
                                        <th class="cell">Categoria</th>
                                        <th class="cell">Stock</th>
                                        <th class="cell">Precio venta</th>
                                        <th class="cell">Historico</th>
                                        <th class="cell">Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for producto in productos %}
                                    <tr>
                                        <td class="cell">{{producto.IdProducto|intcomma}}</td>
                                        <td class="cell">{{producto.NombreProducto}}</td>
                                        <td class="cell">{{producto.Categoria}}</td>
                                        <td class="cell">{{producto.Stock}}</td>
                                        <td class="cell"><span>${{producto.PrecioVenta|intcomma}}</span><span class="note">{{producto.Fecha}}</span></td>
                                        <td class="cell">{{producto.Historico}}</td>
                                        <td class="cell"><a class="btn-sm app-btn-secondary" href="{% url 'usuarios:agregarstock' producto.IdProducto %}">Stock</a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!--//row-->
{% endblock %}
{% block scripts %}
<script>
 // Write on keyup event of keyword input element
 $(document).ready(function(){
 $("#search").keyup(function(){
 _this = this;
 // Show only matching TR, hide rest of them
 $.each($("#dataTable tbody tr"), function() {
 if($(this).text().toLowerCase().indexOf($(_this).val().toLowerCase()) === -1)
 $(this).hide();
 else
 $(this).show();
 });
 });
});
</script>
{% endblock %}